

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import MySessionProvider from "@/components/my-session-provider";
import { getServerSession } from "next-auth"; // ⬅️ Import this
import { authOptions } from "@/app/api/auth/[...nextauth]/options"; // ⬅️ Your NextAuth config


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};





export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions); // ⬅️ Fetch session here






  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MySessionProvider session={session}> {/* ⬅️ Pass session here */}
            <SidebarProvider>
              <AppSidebar />
              <SidebarTrigger />
              {children}
              <Toaster />
            </SidebarProvider>
          </MySessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
